# Use "localhost" for development environment
Domain = "learningbay24.de"
# Using https?
Secure = true
# Populate the development database with dummy data
Environment = "development"
LogLevel = "info"
AdminPass = "changethis"

[DB]
Host = "127.0.0.1"
Port = 3306
# default user/pass/db for docker-compose file in contrib/ dir
User = "learningbay24"
Pass = "learningbay24"
Database = "learningbay24"

[Files]
Path = "/var/lib/learningbay24/"
AllowedFileTypes = ["pdf", "png", "jpg", "zip", "tar", "gz", "bzip", "rar", "txt"]
# maximum number of bytes in files a user can upload in total
# 0 = disable
MaxUploadPerUser = 0

[Secrets]
JWTSecret = "changethis"
